@startuml
class Produto {
    code : Integer
    url : String
    creator : String
    created_t : Integer
    last_modified_t : Integer
    product_name : String
    quantity : String
    brands : String
    categories : String
    labels : String
    cities : String
    purchase_places : String
    stores : String
    ingredients_text : String
    traces : String
    serving_size : String
    serving_quantity : Float
    nutriscore_score : Integer
    nutriscore_grade : String
    main_category : String
    image_url : String
    status : String
    imported_t : DateTime
    updated_at : DateTime
    created_at : DateTime
}
@enduml
